// Code generated by "stringer -type strategy"; DO NOT EDIT.

package lseq

import "fmt"

const _strategy_name = "undefinedStrategyboundaryLoStrategyboundaryHiStrategystategyCount"

var _strategy_index = [...]uint8{0, 17, 35, 53, 65}

func (i strategy) String() string {
	if i >= strategy(len(_strategy_index)-1) {
		return fmt.Sprintf("strategy(%d)", i)
	}
	return _strategy_name[_strategy_index[i]:_strategy_index[i+1]]
}
